import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['src/test/setup.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      include: ['src/**'],
      exclude: [
        'src/main.tsx',
        'src/test/**',
        '**/*.d.ts',
        'src/config/**',
        'src/data/**',
        'src/pages/**',
        'src/styles/**',
        'src/types/**',
        'src/auth/**',
        'src/App.tsx',
        'src/App.css',
        'src/index.css',
        'src/assets/**',
        'src/services/api.ts',
        'src/services/db.ts',
        '**/*.module.css',
        // Components not yet tested
        'src/components/auth/**',
        'src/components/common/**',
        'src/components/entry/EntryList.tsx',
        'src/components/entry/EntryForm.tsx',
        'src/components/entry/ChipInput.tsx',
        'src/components/entry/EnrichmentPanel.tsx',
        'src/components/entry/LearningScoreBar.tsx',
        'src/components/entry/PartOfSpeechSelector.tsx',
        'src/components/entry/TagInput.tsx',
        'src/components/phrasebook/**',
        'src/components/layout/**',
        'src/components/ui/**',
        'src/components/review/**',
        'src/components/search/FilterPanel.tsx',
        'src/components/search/SearchField.tsx',
        'src/components/search/SortDropdown.tsx',
        'src/components/search/filterTypes.ts',
        'src/components/tags/**',
        // Hooks not yet tested
        'src/hooks/InstallPromptContext.tsx',
        'src/hooks/installPromptCtx.ts',
        'src/hooks/useBackButtonExit.ts',
        'src/hooks/useInstallPrompt.tsx',
      ],
      thresholds: {
        lines: 50,
        functions: 50,
        branches: 50,
      },
    },
  },
});
