import type { PhrasebookDefinition } from './generators.js';

export const phrasebooks: PhrasebookDefinition[] = [
  // ── English → Italian ───────────────────────────────────────────────────────
  {
    name: 'Italian Essentials',
    sourceLanguageCode: 'en',
    sourceLanguageName: 'English',
    targetLanguageCode: 'it',
    targetLanguageName: 'Italian',
    entries: [
      { sourceText: 'hello', targetText: 'ciao', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'goodbye', targetText: 'arrivederci', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'please', targetText: 'per favore', tags: ['basics'], partOfSpeech: 'adverb' },
      { sourceText: 'thank you', targetText: 'grazie', tags: ['basics'], partOfSpeech: 'interjection' },
      { sourceText: 'good morning', targetText: 'buongiorno', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'good evening', targetText: 'buonasera', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'good night', targetText: 'buonanotte', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'yes', targetText: 'sì', tags: ['basics'], partOfSpeech: 'adverb' },
      { sourceText: 'no', targetText: 'no', tags: ['basics'], partOfSpeech: 'adverb' },
      { sourceText: 'excuse me', targetText: 'mi scusi', tags: ['basics'], partOfSpeech: 'expression' },
      { sourceText: 'water', targetText: 'acqua', tags: ['food', 'basics'], partOfSpeech: 'noun' },
      { sourceText: 'bread', targetText: 'pane', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'coffee', targetText: 'caffè', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'wine', targetText: 'vino', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'cheese', targetText: 'formaggio', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'ice cream', targetText: 'gelato', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'the bill', targetText: 'il conto', tags: ['restaurant'], partOfSpeech: 'noun', notes: 'Used when asking for the check at a restaurant' },
      { sourceText: 'breakfast', targetText: 'colazione', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'lunch', targetText: 'pranzo', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'dinner', targetText: 'cena', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'to eat', targetText: 'mangiare', tags: ['food'], partOfSpeech: 'verb' },
      { sourceText: 'to drink', targetText: 'bere', tags: ['food'], partOfSpeech: 'verb' },
      { sourceText: 'to speak', targetText: 'parlare', tags: ['communication'], partOfSpeech: 'verb' },
      { sourceText: 'to understand', targetText: 'capire', tags: ['communication'], partOfSpeech: 'verb' },
      { sourceText: 'to go', targetText: 'andare', tags: ['travel'], partOfSpeech: 'verb' },
      { sourceText: 'to come', targetText: 'venire', tags: ['travel'], partOfSpeech: 'verb' },
      { sourceText: 'to want', targetText: 'volere', tags: ['basics'], partOfSpeech: 'verb' },
      { sourceText: 'to be able to', targetText: 'potere', tags: ['basics'], partOfSpeech: 'verb' },
      { sourceText: 'to have to', targetText: 'dovere', tags: ['basics'], partOfSpeech: 'verb' },
      { sourceText: 'beautiful', targetText: 'bello', tags: ['adjectives'], partOfSpeech: 'adjective', notes: 'Changes form: bello/bella/belli/belle' },
      { sourceText: 'big', targetText: 'grande', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'small', targetText: 'piccolo', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'happy', targetText: 'felice', tags: ['emotions'], partOfSpeech: 'adjective' },
      { sourceText: 'sad', targetText: 'triste', tags: ['emotions'], partOfSpeech: 'adjective' },
      { sourceText: 'tired', targetText: 'stanco', tags: ['emotions'], partOfSpeech: 'adjective' },
      { sourceText: 'train station', targetText: 'stazione ferroviaria', tags: ['travel'], partOfSpeech: 'noun' },
      { sourceText: 'airport', targetText: 'aeroporto', tags: ['travel'], partOfSpeech: 'noun' },
      { sourceText: 'hotel', targetText: 'albergo', tags: ['travel'], partOfSpeech: 'noun' },
      { sourceText: 'museum', targetText: 'museo', tags: ['travel', 'culture'], partOfSpeech: 'noun' },
      { sourceText: 'beach', targetText: 'spiaggia', tags: ['travel', 'nature'], partOfSpeech: 'noun' },
      { sourceText: 'church', targetText: 'chiesa', tags: ['travel', 'culture'], partOfSpeech: 'noun' },
      { sourceText: 'how much does it cost?', targetText: 'quanto costa?', tags: ['shopping'], partOfSpeech: 'expression' },
      { sourceText: 'where is...?', targetText: 'dove si trova...?', tags: ['travel'], partOfSpeech: 'expression' },
      { sourceText: 'I would like', targetText: 'vorrei', tags: ['restaurant', 'shopping'], partOfSpeech: 'verb', notes: 'Conditional form of volere — polite way to order' },
      { sourceText: 'left', targetText: 'sinistra', tags: ['directions'], partOfSpeech: 'noun' },
      { sourceText: 'right', targetText: 'destra', tags: ['directions'], partOfSpeech: 'noun' },
      { sourceText: 'straight ahead', targetText: 'dritto', tags: ['directions'], partOfSpeech: 'adverb' },
      { sourceText: 'street', targetText: 'via', tags: ['travel', 'directions'], partOfSpeech: 'noun' },
      { sourceText: 'sun', targetText: 'sole', tags: ['nature'], partOfSpeech: 'noun' },
      { sourceText: 'sea', targetText: 'mare', tags: ['nature'], partOfSpeech: 'noun' },
    ],
  },

  // ── English → Spanish ──────────────────────────────────────────────────────
  {
    name: 'Spanish Basics',
    sourceLanguageCode: 'en',
    sourceLanguageName: 'English',
    targetLanguageCode: 'es',
    targetLanguageName: 'Spanish',
    entries: [
      { sourceText: 'hello', targetText: 'hola', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'goodbye', targetText: 'adiós', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'please', targetText: 'por favor', tags: ['basics'], partOfSpeech: 'adverb' },
      { sourceText: 'thank you', targetText: 'gracias', tags: ['basics'], partOfSpeech: 'interjection' },
      { sourceText: 'good morning', targetText: 'buenos días', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'good afternoon', targetText: 'buenas tardes', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'how are you?', targetText: 'cómo estás?', tags: ['greetings'], partOfSpeech: 'expression', notes: 'Informal; use cómo está? for formal' },
      { sourceText: 'I don\'t understand', targetText: 'no entiendo', tags: ['communication'], partOfSpeech: 'expression' },
      { sourceText: 'do you speak english?', targetText: 'hablas inglés?', tags: ['communication'], partOfSpeech: 'expression' },
      { sourceText: 'water', targetText: 'agua', tags: ['food'], partOfSpeech: 'noun', notes: 'Feminine but uses "el" — el agua' },
      { sourceText: 'beer', targetText: 'cerveza', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'chicken', targetText: 'pollo', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'rice', targetText: 'arroz', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'fish', targetText: 'pescado', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'fruit', targetText: 'fruta', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'to eat', targetText: 'comer', tags: ['food'], partOfSpeech: 'verb' },
      { sourceText: 'to drink', targetText: 'beber', tags: ['food'], partOfSpeech: 'verb' },
      { sourceText: 'to sleep', targetText: 'dormir', tags: ['daily life'], partOfSpeech: 'verb' },
      { sourceText: 'to work', targetText: 'trabajar', tags: ['work'], partOfSpeech: 'verb' },
      { sourceText: 'to study', targetText: 'estudiar', tags: ['work'], partOfSpeech: 'verb' },
      { sourceText: 'to travel', targetText: 'viajar', tags: ['travel'], partOfSpeech: 'verb' },
      { sourceText: 'to buy', targetText: 'comprar', tags: ['shopping'], partOfSpeech: 'verb' },
      { sourceText: 'to pay', targetText: 'pagar', tags: ['shopping'], partOfSpeech: 'verb' },
      { sourceText: 'to help', targetText: 'ayudar', tags: ['basics'], partOfSpeech: 'verb' },
      { sourceText: 'to know', targetText: 'saber', tags: ['basics'], partOfSpeech: 'verb', notes: 'saber = know facts; conocer = know people/places' },
      { sourceText: 'house', targetText: 'casa', tags: ['daily life'], partOfSpeech: 'noun' },
      { sourceText: 'family', targetText: 'familia', tags: ['daily life'], partOfSpeech: 'noun' },
      { sourceText: 'friend', targetText: 'amigo', tags: ['daily life'], partOfSpeech: 'noun', notes: 'amigo (m) / amiga (f)' },
      { sourceText: 'book', targetText: 'libro', tags: ['culture'], partOfSpeech: 'noun' },
      { sourceText: 'money', targetText: 'dinero', tags: ['shopping'], partOfSpeech: 'noun' },
      { sourceText: 'time', targetText: 'tiempo', tags: ['basics'], partOfSpeech: 'noun', notes: 'Also means "weather"' },
      { sourceText: 'day', targetText: 'día', tags: ['time'], partOfSpeech: 'noun' },
      { sourceText: 'night', targetText: 'noche', tags: ['time'], partOfSpeech: 'noun' },
      { sourceText: 'today', targetText: 'hoy', tags: ['time'], partOfSpeech: 'adverb' },
      { sourceText: 'tomorrow', targetText: 'mañana', tags: ['time'], partOfSpeech: 'adverb', notes: 'Also means "morning" as a noun' },
      { sourceText: 'hot', targetText: 'caliente', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'cold', targetText: 'frío', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'good', targetText: 'bueno', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'bad', targetText: 'malo', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'new', targetText: 'nuevo', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'old', targetText: 'viejo', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'fast', targetText: 'rápido', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'slow', targetText: 'lento', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'bathroom', targetText: 'baño', tags: ['travel'], partOfSpeech: 'noun' },
      { sourceText: 'hospital', targetText: 'hospital', tags: ['emergency'], partOfSpeech: 'noun' },
      { sourceText: 'pharmacy', targetText: 'farmacia', tags: ['emergency'], partOfSpeech: 'noun' },
      { sourceText: 'market', targetText: 'mercado', tags: ['shopping'], partOfSpeech: 'noun' },
      { sourceText: 'to run', targetText: 'correr', tags: ['daily life'], partOfSpeech: 'verb' },
      { sourceText: 'to walk', targetText: 'caminar', tags: ['travel'], partOfSpeech: 'verb' },
      { sourceText: 'mountain', targetText: 'montaña', tags: ['nature'], partOfSpeech: 'noun' },
    ],
  },

  // ── English → French ───────────────────────────────────────────────────────
  {
    name: 'French Foundations',
    sourceLanguageCode: 'en',
    sourceLanguageName: 'English',
    targetLanguageCode: 'fr',
    targetLanguageName: 'French',
    entries: [
      { sourceText: 'hello', targetText: 'bonjour', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'goodbye', targetText: 'au revoir', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'please', targetText: 's\'il vous plaît', tags: ['basics'], partOfSpeech: 'expression', notes: 'Formal; s\'il te plaît for informal' },
      { sourceText: 'thank you', targetText: 'merci', tags: ['basics'], partOfSpeech: 'interjection' },
      { sourceText: 'yes', targetText: 'oui', tags: ['basics'], partOfSpeech: 'adverb' },
      { sourceText: 'no', targetText: 'non', tags: ['basics'], partOfSpeech: 'adverb' },
      { sourceText: 'sorry', targetText: 'pardon', tags: ['basics'], partOfSpeech: 'interjection' },
      { sourceText: 'how are you?', targetText: 'comment allez-vous ?', tags: ['greetings'], partOfSpeech: 'expression' },
      { sourceText: 'I am fine', targetText: 'je vais bien', tags: ['greetings'], partOfSpeech: 'expression' },
      { sourceText: 'my name is', targetText: 'je m\'appelle', tags: ['greetings'], partOfSpeech: 'expression' },
      { sourceText: 'bread', targetText: 'pain', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'butter', targetText: 'beurre', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'croissant', targetText: 'croissant', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'milk', targetText: 'lait', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'meat', targetText: 'viande', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'cake', targetText: 'gâteau', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'the menu', targetText: 'la carte', tags: ['restaurant'], partOfSpeech: 'noun', notes: 'le menu = fixed-price set meal' },
      { sourceText: 'to eat', targetText: 'manger', tags: ['food'], partOfSpeech: 'verb' },
      { sourceText: 'to drink', targetText: 'boire', tags: ['food'], partOfSpeech: 'verb' },
      { sourceText: 'to go', targetText: 'aller', tags: ['travel'], partOfSpeech: 'verb' },
      { sourceText: 'to see', targetText: 'voir', tags: ['basics'], partOfSpeech: 'verb' },
      { sourceText: 'to do / to make', targetText: 'faire', tags: ['basics'], partOfSpeech: 'verb' },
      { sourceText: 'to take', targetText: 'prendre', tags: ['basics'], partOfSpeech: 'verb' },
      { sourceText: 'to give', targetText: 'donner', tags: ['basics'], partOfSpeech: 'verb' },
      { sourceText: 'to speak', targetText: 'parler', tags: ['communication'], partOfSpeech: 'verb' },
      { sourceText: 'to read', targetText: 'lire', tags: ['culture'], partOfSpeech: 'verb' },
      { sourceText: 'to write', targetText: 'écrire', tags: ['culture'], partOfSpeech: 'verb' },
      { sourceText: 'to live', targetText: 'vivre', tags: ['daily life'], partOfSpeech: 'verb' },
      { sourceText: 'to love', targetText: 'aimer', tags: ['emotions'], partOfSpeech: 'verb' },
      { sourceText: 'man', targetText: 'homme', tags: ['daily life'], partOfSpeech: 'noun' },
      { sourceText: 'woman', targetText: 'femme', tags: ['daily life'], partOfSpeech: 'noun', notes: 'Also means "wife"' },
      { sourceText: 'child', targetText: 'enfant', tags: ['daily life'], partOfSpeech: 'noun' },
      { sourceText: 'city', targetText: 'ville', tags: ['travel'], partOfSpeech: 'noun' },
      { sourceText: 'country', targetText: 'pays', tags: ['travel'], partOfSpeech: 'noun' },
      { sourceText: 'school', targetText: 'école', tags: ['work'], partOfSpeech: 'noun' },
      { sourceText: 'work', targetText: 'travail', tags: ['work'], partOfSpeech: 'noun' },
      { sourceText: 'car', targetText: 'voiture', tags: ['travel'], partOfSpeech: 'noun' },
      { sourceText: 'train', targetText: 'train', tags: ['travel'], partOfSpeech: 'noun' },
      { sourceText: 'beautiful', targetText: 'beau', tags: ['adjectives'], partOfSpeech: 'adjective', notes: 'beau (m) / belle (f)' },
      { sourceText: 'young', targetText: 'jeune', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'expensive', targetText: 'cher', tags: ['shopping'], partOfSpeech: 'adjective', notes: 'Also means "dear" (term of endearment)' },
      { sourceText: 'cheap', targetText: 'bon marché', tags: ['shopping'], partOfSpeech: 'adjective' },
      { sourceText: 'always', targetText: 'toujours', tags: ['basics'], partOfSpeech: 'adverb' },
      { sourceText: 'never', targetText: 'jamais', tags: ['basics'], partOfSpeech: 'adverb' },
      { sourceText: 'rain', targetText: 'pluie', tags: ['nature'], partOfSpeech: 'noun' },
      { sourceText: 'flower', targetText: 'fleur', tags: ['nature'], partOfSpeech: 'noun' },
      { sourceText: 'tree', targetText: 'arbre', tags: ['nature'], partOfSpeech: 'noun' },
      { sourceText: 'river', targetText: 'fleuve', tags: ['nature'], partOfSpeech: 'noun', notes: 'fleuve flows to the sea; rivière is a tributary' },
    ],
  },

  // ── English → German ───────────────────────────────────────────────────────
  {
    name: 'German Starter',
    sourceLanguageCode: 'en',
    sourceLanguageName: 'English',
    targetLanguageCode: 'de',
    targetLanguageName: 'German',
    entries: [
      { sourceText: 'hello', targetText: 'hallo', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'goodbye', targetText: 'auf Wiedersehen', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'please', targetText: 'bitte', tags: ['basics'], partOfSpeech: 'adverb', notes: 'Also means "you\'re welcome"' },
      { sourceText: 'thank you', targetText: 'danke', tags: ['basics'], partOfSpeech: 'interjection' },
      { sourceText: 'good morning', targetText: 'guten Morgen', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'good evening', targetText: 'guten Abend', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'yes', targetText: 'ja', tags: ['basics'], partOfSpeech: 'adverb' },
      { sourceText: 'no', targetText: 'nein', tags: ['basics'], partOfSpeech: 'adverb' },
      { sourceText: 'I don\'t understand', targetText: 'ich verstehe nicht', tags: ['communication'], partOfSpeech: 'expression' },
      { sourceText: 'do you speak english?', targetText: 'sprechen Sie Englisch?', tags: ['communication'], partOfSpeech: 'expression' },
      { sourceText: 'water', targetText: 'Wasser', tags: ['food'], partOfSpeech: 'noun', notes: 'Neuter: das Wasser' },
      { sourceText: 'bread', targetText: 'Brot', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'sausage', targetText: 'Wurst', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'beer', targetText: 'Bier', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'cake', targetText: 'Kuchen', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'apple', targetText: 'Apfel', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'to eat', targetText: 'essen', tags: ['food'], partOfSpeech: 'verb' },
      { sourceText: 'to drink', targetText: 'trinken', tags: ['food'], partOfSpeech: 'verb' },
      { sourceText: 'to go', targetText: 'gehen', tags: ['travel'], partOfSpeech: 'verb' },
      { sourceText: 'to come', targetText: 'kommen', tags: ['travel'], partOfSpeech: 'verb' },
      { sourceText: 'to speak', targetText: 'sprechen', tags: ['communication'], partOfSpeech: 'verb' },
      { sourceText: 'to learn', targetText: 'lernen', tags: ['work'], partOfSpeech: 'verb' },
      { sourceText: 'to work', targetText: 'arbeiten', tags: ['work'], partOfSpeech: 'verb' },
      { sourceText: 'to live', targetText: 'wohnen', tags: ['daily life'], partOfSpeech: 'verb', notes: 'wohnen = reside; leben = be alive' },
      { sourceText: 'to buy', targetText: 'kaufen', tags: ['shopping'], partOfSpeech: 'verb' },
      { sourceText: 'to read', targetText: 'lesen', tags: ['culture'], partOfSpeech: 'verb' },
      { sourceText: 'to write', targetText: 'schreiben', tags: ['culture'], partOfSpeech: 'verb' },
      { sourceText: 'to think', targetText: 'denken', tags: ['basics'], partOfSpeech: 'verb' },
      { sourceText: 'to find', targetText: 'finden', tags: ['basics'], partOfSpeech: 'verb' },
      { sourceText: 'big', targetText: 'groß', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'small', targetText: 'klein', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'fast', targetText: 'schnell', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'slow', targetText: 'langsam', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'beautiful', targetText: 'schön', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'difficult', targetText: 'schwierig', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'easy', targetText: 'einfach', tags: ['adjectives'], partOfSpeech: 'adjective' },
      { sourceText: 'dog', targetText: 'Hund', tags: ['nature'], partOfSpeech: 'noun' },
      { sourceText: 'cat', targetText: 'Katze', tags: ['nature'], partOfSpeech: 'noun' },
      { sourceText: 'forest', targetText: 'Wald', tags: ['nature'], partOfSpeech: 'noun' },
      { sourceText: 'mountain', targetText: 'Berg', tags: ['nature'], partOfSpeech: 'noun' },
      { sourceText: 'doctor', targetText: 'Arzt', tags: ['emergency'], partOfSpeech: 'noun', notes: 'Arzt (m) / Ärztin (f)' },
      { sourceText: 'hospital', targetText: 'Krankenhaus', tags: ['emergency'], partOfSpeech: 'noun' },
      { sourceText: 'ticket', targetText: 'Fahrkarte', tags: ['travel'], partOfSpeech: 'noun' },
      { sourceText: 'to drive', targetText: 'fahren', tags: ['travel'], partOfSpeech: 'verb' },
      { sourceText: 'to fly', targetText: 'fliegen', tags: ['travel'], partOfSpeech: 'verb' },
    ],
  },

  // ── English → Japanese ─────────────────────────────────────────────────────
  {
    name: 'Japanese Phrases',
    sourceLanguageCode: 'en',
    sourceLanguageName: 'English',
    targetLanguageCode: 'ja',
    targetLanguageName: 'Japanese',
    entries: [
      { sourceText: 'hello', targetText: 'こんにちは', tags: ['greetings'], partOfSpeech: 'interjection', notes: 'konnichiwa — used during daytime' },
      { sourceText: 'goodbye', targetText: 'さようなら', tags: ['greetings'], partOfSpeech: 'interjection', notes: 'sayōnara — formal; じゃあね (jaa ne) is casual' },
      { sourceText: 'good morning', targetText: 'おはようございます', tags: ['greetings'], partOfSpeech: 'interjection', notes: 'ohayō gozaimasu — polite form' },
      { sourceText: 'good evening', targetText: 'こんばんは', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'thank you', targetText: 'ありがとうございます', tags: ['basics'], partOfSpeech: 'interjection', notes: 'arigatō gozaimasu — polite; ありがとう is casual' },
      { sourceText: 'excuse me', targetText: 'すみません', tags: ['basics'], partOfSpeech: 'interjection', notes: 'sumimasen — apology + getting attention' },
      { sourceText: 'please', targetText: 'お願いします', tags: ['basics'], partOfSpeech: 'expression', notes: 'onegaishimasu — used when requesting something' },
      { sourceText: 'yes', targetText: 'はい', tags: ['basics'], partOfSpeech: 'adverb' },
      { sourceText: 'no', targetText: 'いいえ', tags: ['basics'], partOfSpeech: 'adverb' },
      { sourceText: 'water', targetText: '水', tags: ['food'], partOfSpeech: 'noun', notes: 'mizu' },
      { sourceText: 'rice', targetText: 'ご飯', tags: ['food'], partOfSpeech: 'noun', notes: 'gohan — also means "meal"' },
      { sourceText: 'tea', targetText: 'お茶', tags: ['food'], partOfSpeech: 'noun', notes: 'ocha — green tea by default' },
      { sourceText: 'fish', targetText: '魚', tags: ['food'], partOfSpeech: 'noun', notes: 'sakana' },
      { sourceText: 'delicious', targetText: 'おいしい', tags: ['food'], partOfSpeech: 'adjective', notes: 'oishii' },
      { sourceText: 'the bill', targetText: 'お会計', tags: ['restaurant'], partOfSpeech: 'noun', notes: 'okaikei' },
      { sourceText: 'to eat', targetText: '食べる', tags: ['food'], partOfSpeech: 'verb', notes: 'taberu' },
      { sourceText: 'to drink', targetText: '飲む', tags: ['food'], partOfSpeech: 'verb', notes: 'nomu' },
      { sourceText: 'to go', targetText: '行く', tags: ['travel'], partOfSpeech: 'verb', notes: 'iku' },
      { sourceText: 'to come', targetText: '来る', tags: ['travel'], partOfSpeech: 'verb', notes: 'kuru — irregular verb' },
      { sourceText: 'to see / to look', targetText: '見る', tags: ['basics'], partOfSpeech: 'verb', notes: 'miru' },
      { sourceText: 'to speak', targetText: '話す', tags: ['communication'], partOfSpeech: 'verb', notes: 'hanasu' },
      { sourceText: 'to understand', targetText: '分かる', tags: ['communication'], partOfSpeech: 'verb', notes: 'wakaru' },
      { sourceText: 'to buy', targetText: '買う', tags: ['shopping'], partOfSpeech: 'verb', notes: 'kau' },
      { sourceText: 'to read', targetText: '読む', tags: ['culture'], partOfSpeech: 'verb', notes: 'yomu' },
      { sourceText: 'to write', targetText: '書く', tags: ['culture'], partOfSpeech: 'verb', notes: 'kaku' },
      { sourceText: 'to wait', targetText: '待つ', tags: ['basics'], partOfSpeech: 'verb', notes: 'matsu' },
      { sourceText: 'big', targetText: '大きい', tags: ['adjectives'], partOfSpeech: 'adjective', notes: 'ōkii' },
      { sourceText: 'small', targetText: '小さい', tags: ['adjectives'], partOfSpeech: 'adjective', notes: 'chiisai' },
      { sourceText: 'expensive', targetText: '高い', tags: ['shopping'], partOfSpeech: 'adjective', notes: 'takai — also means "tall"' },
      { sourceText: 'cheap', targetText: '安い', tags: ['shopping'], partOfSpeech: 'adjective', notes: 'yasui' },
      { sourceText: 'new', targetText: '新しい', tags: ['adjectives'], partOfSpeech: 'adjective', notes: 'atarashii' },
      { sourceText: 'old', targetText: '古い', tags: ['adjectives'], partOfSpeech: 'adjective', notes: 'furui — for objects; 年取った for people' },
      { sourceText: 'station', targetText: '駅', tags: ['travel'], partOfSpeech: 'noun', notes: 'eki' },
      { sourceText: 'hospital', targetText: '病院', tags: ['emergency'], partOfSpeech: 'noun', notes: 'byōin' },
      { sourceText: 'where is...?', targetText: '...はどこですか?', tags: ['travel'], partOfSpeech: 'expression' },
      { sourceText: 'how much?', targetText: 'いくらですか?', tags: ['shopping'], partOfSpeech: 'expression' },
      { sourceText: 'beautiful', targetText: '美しい', tags: ['adjectives'], partOfSpeech: 'adjective', notes: 'utsukushii — literary; きれい (kirei) is more common' },
      { sourceText: 'mountain', targetText: '山', tags: ['nature'], partOfSpeech: 'noun', notes: 'yama' },
      { sourceText: 'river', targetText: '川', tags: ['nature'], partOfSpeech: 'noun', notes: 'kawa' },
      { sourceText: 'cherry blossom', targetText: '桜', tags: ['nature', 'culture'], partOfSpeech: 'noun', notes: 'sakura' },
    ],
  },

  // ── English → Portuguese ───────────────────────────────────────────────────
  {
    name: 'Portuguese Travel',
    sourceLanguageCode: 'en',
    sourceLanguageName: 'English',
    targetLanguageCode: 'pt',
    targetLanguageName: 'Portuguese',
    entries: [
      { sourceText: 'hello', targetText: 'olá', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'goodbye', targetText: 'tchau', tags: ['greetings'], partOfSpeech: 'interjection', notes: 'Informal; adeus is more formal' },
      { sourceText: 'please', targetText: 'por favor', tags: ['basics'], partOfSpeech: 'adverb' },
      { sourceText: 'thank you', targetText: 'obrigado', tags: ['basics'], partOfSpeech: 'interjection', notes: 'obrigado (m) / obrigada (f)' },
      { sourceText: 'good morning', targetText: 'bom dia', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'good afternoon', targetText: 'boa tarde', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'good night', targetText: 'boa noite', tags: ['greetings'], partOfSpeech: 'interjection' },
      { sourceText: 'how are you?', targetText: 'como está?', tags: ['greetings'], partOfSpeech: 'expression', notes: 'Formal; como estás? or tudo bem? informal' },
      { sourceText: 'I don\'t speak portuguese', targetText: 'eu não falo português', tags: ['communication'], partOfSpeech: 'expression' },
      { sourceText: 'do you speak english?', targetText: 'fala inglês?', tags: ['communication'], partOfSpeech: 'expression' },
      { sourceText: 'water', targetText: 'água', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'coffee', targetText: 'café', tags: ['food'], partOfSpeech: 'noun', notes: 'In Portugal, just "um café" gets you an espresso' },
      { sourceText: 'bread', targetText: 'pão', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'chicken', targetText: 'frango', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'fish', targetText: 'peixe', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'egg', targetText: 'ovo', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'salt', targetText: 'sal', tags: ['food'], partOfSpeech: 'noun' },
      { sourceText: 'to eat', targetText: 'comer', tags: ['food'], partOfSpeech: 'verb' },
      { sourceText: 'to drink', targetText: 'beber', tags: ['food'], partOfSpeech: 'verb' },
      { sourceText: 'to go', targetText: 'ir', tags: ['travel'], partOfSpeech: 'verb' },
      { sourceText: 'to come', targetText: 'vir', tags: ['travel'], partOfSpeech: 'verb' },
      { sourceText: 'to speak', targetText: 'falar', tags: ['communication'], partOfSpeech: 'verb' },
      { sourceText: 'to want', targetText: 'querer', tags: ['basics'], partOfSpeech: 'verb' },
      { sourceText: 'to need', targetText: 'precisar', tags: ['basics'], partOfSpeech: 'verb' },
      { sourceText: 'to pay', targetText: 'pagar', tags: ['shopping'], partOfSpeech: 'verb' },
      { sourceText: 'to wait', targetText: 'esperar', tags: ['basics'], partOfSpeech: 'verb', notes: 'Also means "to hope"' },
      { sourceText: 'to know', targetText: 'saber', tags: ['basics'], partOfSpeech: 'verb', notes: 'saber = know facts; conhecer = know people/places' },
      { sourceText: 'to like', targetText: 'gostar', tags: ['emotions'], partOfSpeech: 'verb', notes: 'Requires "de": gosto de café' },
      { sourceText: 'beach', targetText: 'praia', tags: ['travel', 'nature'], partOfSpeech: 'noun' },
      { sourceText: 'sun', targetText: 'sol', tags: ['nature'], partOfSpeech: 'noun' },
      { sourceText: 'sea', targetText: 'mar', tags: ['nature'], partOfSpeech: 'noun' },
      { sourceText: 'ticket', targetText: 'bilhete', tags: ['travel'], partOfSpeech: 'noun' },
      { sourceText: 'map', targetText: 'mapa', tags: ['travel'], partOfSpeech: 'noun' },
      { sourceText: 'left', targetText: 'esquerda', tags: ['directions'], partOfSpeech: 'noun' },
      { sourceText: 'right', targetText: 'direita', tags: ['directions'], partOfSpeech: 'noun' },
      { sourceText: 'straight ahead', targetText: 'em frente', tags: ['directions'], partOfSpeech: 'adverb' },
      { sourceText: 'beautiful', targetText: 'bonito', tags: ['adjectives'], partOfSpeech: 'adjective', notes: 'bonito (m) / bonita (f)' },
      { sourceText: 'happy', targetText: 'feliz', tags: ['emotions'], partOfSpeech: 'adjective' },
      { sourceText: 'tired', targetText: 'cansado', tags: ['emotions'], partOfSpeech: 'adjective' },
      { sourceText: 'hungry', targetText: 'com fome', tags: ['food'], partOfSpeech: 'expression', notes: 'Literally "with hunger"' },
      { sourceText: 'how much does it cost?', targetText: 'quanto custa?', tags: ['shopping'], partOfSpeech: 'expression' },
      { sourceText: 'where is...?', targetText: 'onde fica...?', tags: ['travel'], partOfSpeech: 'expression' },
      { sourceText: 'open', targetText: 'aberto', tags: ['daily life'], partOfSpeech: 'adjective' },
      { sourceText: 'closed', targetText: 'fechado', tags: ['daily life'], partOfSpeech: 'adjective' },
      { sourceText: 'rain', targetText: 'chuva', tags: ['nature'], partOfSpeech: 'noun' },
    ],
  },

  // ── Decay showcase (deterministic, for local testing) ─────────────────────
  // Each entry is fixed to a specific DecayBadge state so all visual states
  // can be reviewed in a single seed run. Labels use [DECAY:…] prefix so they
  // stand out in the list.
  {
    name: '🧪 Decay Showcase',
    sourceLanguageCode: 'en',
    sourceLanguageName: 'English',
    targetLanguageCode: 'en',
    targetLanguageName: 'English (labels)',
    entries: [
      {
        sourceText: 'DECAY: none',
        targetText: 'never reviewed',
        notes: 'No badge expected. decayBaseScore = null.',
        tags: ['decay-showcase'],
        decayScenario: 'none',
      },
      {
        sourceText: 'DECAY: fresh',
        targetText: 'green strip, safe',
        notes: 'Reviewed 3 days ago. Engraved (base=85, grace=21d). 18 days left → fresh zone.',
        tags: ['decay-showcase'],
        decayScenario: 'fresh',
      },
      {
        sourceText: 'DECAY: grace warning',
        targetText: 'amber strip, 4 days left',
        notes: 'Reviewed 17 days ago. Engraved (base=85, grace=21d). 4 days left → last 25% → warning.',
        tags: ['decay-showcase'],
        decayScenario: 'graceWarning',
      },
      {
        sourceText: 'DECAY: low',
        targetText: 'amber strip, -3 pts',
        notes: 'Reviewed 30 days ago. Engraved (base=80, grace=21d). 9d past grace → −3 pts (3.75%) → low.',
        tags: ['decay-showcase'],
        decayScenario: 'decayLow',
      },
      {
        sourceText: 'DECAY: medium',
        targetText: 'orange strip, -9 pts',
        notes: 'Reviewed 34 days ago. Echoing (base=50, grace=7d). 27d past grace → −9 pts (18%) → medium.',
        tags: ['decay-showcase'],
        decayScenario: 'decayMedium',
      },
      {
        sourceText: 'DECAY: high',
        targetText: 'red strip, -24 pts',
        notes: 'Reviewed 80 days ago. Echoing (base=50, grace=7d). 73d past grace → −24 pts (48%) → high.',
        tags: ['decay-showcase'],
        decayScenario: 'decayHigh',
      },
    ],
  },
];
